const URL_APP = {
    Login: '/Login',
    Auth: '/Auth',
    Signup: '/Signup',
    Logout: '/Logout',
    Categories: '/Categories',
    AddCategory: '/Add_Category',
    Products: '/Products',
    AddProduct: '/Add_Product',
    ProductDetail: '/Product_Detail',
    UpdateProduct: '/Update_Product',
    UserProfile: '/User_Profile',
    Home: '/Home',
    User: '/User',
    AddUser: '/Add_User',
    UpdateUser: '/Update_User',
    UpdateCategory: '/Update_Category',
    MemberShipType: '/Member_Ship_Type',
    AddMemberShipType: '/Add_Member_Ship_Type',
    UpdateMemberShipType: '/Update_Member_Ship_Type',
    Customer: '/Customer',
    AddCustomer: '/Add_Customer',
    UpdateCustomer: '/Update_Customer',
    Attribute: '/Attribute',
    AddAttribute: '/Add_Attribute',
    UpdateAttribute: '/Update_Attribute',
    Employee: '/Employee',
    AddEmployee: '/Add_Employee',
    UpdateEmployee: '/Update_Employee',
    Supplier: '/Supplier',
    AddSupplier: '/Add_Supplier',
    UpdateSupplier: '/Update_Supplier',
    ImportGoods: '/Import_Goods',
    Sale: '/Sale',
};
export { URL_APP };
